config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin panel routing, return 404 unless account is admin
  authenticated :account, ->(account) { account.admin? } do
    namespace :admin do
      resources :accounts, :projects
      namespace :profiles do
        resources :users
      end

      # Analytics Dashboard
      mount Blazer::Engine, at: 'analytics', as: :analytics

      root to: 'accounts#index'
    end
  end

  # Error routing
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Static pages
  get '/platform', to: 'static#github_for_documents'

  devise_for :accounts, skip: %i[registrations sessions]

  # Routes for signups
  post '/signup' => 'signups#create'

  # Routes for registration
  if Settings.enable_account_registration
    devise_scope :account do
      get   '/join' => 'devise/registrations#new',
            :as     => :new_registration
      post  '/join' => 'devise/registrations#create',
            :as     => :registration
    end
  end

  # Routes for account management
  devise_scope :account do
    resource :account,
             only: %i[edit update destroy],
             path_names: { edit: '' },
             controller: 'accounts'
    # Stay on /account page after user updates their account
    get '/account', to: 'accounts#edit', as: :account_root
  end

  # Routes for sessions
  devise_scope :account do
    get   '/login'  => 'devise/sessions#new',
          :as       => :new_session
    post  '/login'  => 'devise/sessions#create',
          :as       => :session
    get   '/logout' => 'devise/sessions#destroy',
          :as       => :destroy_session
  end

  # Redirect to login path when user is unauthenticated
  get '/login' => 'devise/sessions#new', :as => :new_account_session

  # Routes for notifications
  resources :notifications, only: %i[index show]

  # Routes for creating new projects
  get   '/projects/new' => 'projects#new',    as: :new_project
  post  '/projects/new' => 'projects#create', as: :projects

  # Routes for user profiles (must be last)
  resources :profiles, path: '/', only: %i[show edit update], param: :handle

  # Routes for existing projects (must be last)
  resources :profiles, path: '/', only: [], param: :handle do
    # Routes for existing projects (must be last)
    resources :projects,
              path: '/', except: %i[index new create], param: :slug do
      # Route for overview
      get 'overview' => 'project_overviews#show', as: :overview
      # Routes for setup
      resource :project_setup, as: 'setup', only: %i[new create show],
                               path: 'setup'
      # Routes for folders
      get 'files' => 'folders#root', as: :root_folder
      resources :folders, only: :show
      # Routes for revisions
      resources :revisions, only: %i[index new create] do
        scope module: 'revisions' do
          get 'files' => 'folders#root', as: :root_folder
          resources :folders, only: :show

          # revision restorations
          post 'restore' => 'restores#create', as: :restores
          get 'restore/status', to: 'restores#show', as: :restore_status,
                                on: :collection

          resources :file_changes, path: 'changes',
                                   controller: 'file_changes',
                                   only: :show
        end
      end
      # Routes for contributions
      resources :contributions, only: %i[index new create show] do
        scope module: 'contributions' do
          # File browsing
          get 'files' => 'folders#root', as: :root_folder
          resources :folders, only: :show

          # Replies
          resources :replies, only: %i[index create]

          # Review
          resource :review, only: :show
          resource :acceptance, path: 'accept', only: :create

          # Routes for file infos
          resources :file_infos, path: 'files/:id/info', only: :index
          resources :force_syncs, path: 'files/:id/sync', only: :create

          # Side-by-side diffs
          resources :file_changes, path: 'changes', only: :show
        end
      end

      # Routes for changes
      resources :file_changes, path: 'changes', only: :show

      # Routes for file infos
      resources :file_infos, path: 'files/:id/info', only: :index
      resources :force_syncs, path: 'files/:id/sync', only: :create
      resources :file_restores, path: 'versions/:id/restore', only: :create
    end
  end

  root 'static#open_collaboration'
end

app/controllers/abstract/folders_controller.rb
# frozen_string_literal: true

module Abstract
  # Abstract super class for folders controller used for project and
  # contributions
  class FoldersController < ApplicationController
    include CanSetProjectContext

    before_action :authenticate_account!, :require_authentication?
    before_action :set_project_where_setup_is_complete
    before_action :authorize_project_access
    before_action :authorize_action
    before_action :set_object
    before_action :set_branch
    before_action :set_folder_from_param, only: :show
    before_action :set_folder_from_root, only: :root
    before_action :set_children
    before_action :preload_thumbnails_for_children
    before_action :set_ancestors
    before_action :set_user_can_commit_changes

    def root
      render_folders_show
    end

    def show
      render_folders_show
    end

    private

    rescue_from CanCan::AccessDenied do |exception|
      can_can_access_denied(exception)
    end

    def authorize_action
      # Overwrite to authorize the action
    end

    def render_folders_show
      render 'folders/show', locals: {
        path_parameters: path_parameters,
        folder_path: "#{link_path_prefix}folder_path",
        file_infos_path: "#{link_path_prefix}file_infos_path",
        root_folder_path: "#{link_path_prefix}root_folder_path"
      }
    end

    # TODO: Do we still need this method?
    def preload_thumbnails_for_children
      # FileResource::Thumbnail.preload_for(@children)
    end

    def set_ancestors
      @ancestors = @folder.ancestors.to_a
    end

    def set_children
      @children = @folder.children.order_by_name_with_folders_first
    end

    def set_folder_from_param
      @folder =
        @branch
        .folders
        .find_by_hashed_file_id_or_remote_file_id!(params[:id])

      raise ActiveRecord::RecordNotFound unless @folder&.version&.folder?
    end

    def set_folder_from_root
      raise ActiveRecord::RecordNotFound unless @branch.root.present?

      @folder = @branch.root
    end

    # Can the current user capture changes? Defaults to false
    def set_user_can_commit_changes
      @user_can_commit_changes = false
    end

    # @abstract Subclass is expected to implement #set_object
    # @!method set_object
    #   Load the object here, such as the contribution

    # @abstract Subclass is expected to implement #set_branch
    # @!method set_branch
    #   Set the branch here, such as @master_branch or contribution.branch
  end
end

app/controllers/contributions/folders_controller.rb
# frozen_string_literal: true

module Contributions
  # File browsing actions for a project contribution
  class FoldersController < Abstract::FoldersController
    private

    def link_path_prefix
      'profile_project_contribution_'
    end

    def path_parameters
      [@project.owner, @project, @contribution]
    end

    def require_authentication?
      false
    end

    def set_object
      @contribution = @project.contributions.find(params[:contribution_id])
    end

    def set_branch
      @branch = @contribution.branch
    end
  end
end

app/controllers/folders_controller.rb
# frozen_string_literal: true

# Controller for project folders
class FoldersController < Abstract::FoldersController
  private

  def authorize_action
    authorize! :show, :file_in_branch, @project
  end

  def can_can_access_denied(exception)
    super || redirect_to(project_path, alert: exception.message)
  end

  def link_path_prefix
    'profile_project_'
  end

  def path_parameters
    [@project.owner, @project]
  end

  def project_path
    profile_project_path(@project.owner, @project)
  end

  def require_authentication?
    true
  end

  def set_user_can_commit_changes
    @user_can_commit_changes = can?(:new, :revision, @project)
  end

  # We don't need to set an object
  def set_object; end

  def set_branch
    @branch = @master_branch
  end
end

app/controllers/revision/folders_controller.rb
# frozen_string_literal: true

class Revision
  # File browsing actions for a project revision
  class FoldersController < ApplicationController
    include CanSetProjectContext

    before_action :set_project_where_setup_is_complete
    before_action :authorize_project_access
    before_action :set_revision, only: %i[root show]
    before_action :set_folder_from_root, only: :root
    before_action :set_folder_from_param, only: :show
    before_action :set_children, only: %i[root show]
    before_action :preload_backups_for_children, only: %i[root show]

    def root
      render 'show'
    end

    def show; end

    private

    def preload_backups_for_children
      ActiveRecord::Associations::Preloader.new.preload(
        Array(@children).flat_map(&:file_resource_snapshot),
        backup: :file_resource
      )
    end

    def set_children
      @children =
        @revision.committed_files
                 .includes(file_resource_snapshot: [:file_resource])
                 .in_folder(@folder)
                 .order_by_name_with_folders_first
    end

    def set_folder_from_param
      @folder =
        @revision.committed_files
                 .includes(:file_resource)
                 .find_by!(file_resources: { external_id: params[:id] })
                 .file_resource

      # TODO: Don't check if file resource is folder NOW, check if committed
      # =>    file resource snapshot was folder BACK at commit
      raise ActiveRecord::RecordNotFound unless @folder.folder?
    end

    def set_folder_from_root
      @folder = @project.root_folder
    end

    def set_revision
      @revision = @project.revisions.find(params[:revision_id])
    end
  end
end

app/controllers/revisions/folders_controller.rb
# frozen_string_literal: true

module Revisions
  # File browsing actions for a project revision
  class FoldersController < ApplicationController
    include CanSetProjectContext

    before_action :set_project_where_setup_is_complete
    before_action :authorize_project_access
    before_action :set_revision, only: %i[root show]
    before_action :set_folder_from_root, only: :root
    before_action :set_folder_from_param, only: :show
    before_action :set_children, only: %i[root show]
    before_action :set_ancestors, only: %i[root show]
    before_action :set_user_can_restore_revision

    def root
      render 'show'
    end

    def show; end

    private

    # TODO: Refactor into ancestry generator class
    def set_ancestors
      @ancestors = []
      ancestor =
        @revision.committed_versions
                 .find_by(file_id: @folder.parent_id)

      while ancestor.present?
        @ancestors << ancestor
        ancestor =
          @revision.committed_versions
                   .find_by(file_id: ancestor.parent_id)
      end
    end

    def set_children
      @children =
        @revision.committed_versions
                 .includes(:backup, :thumbnail)
                 .where(parent_id: @folder.file_id)
                 .order_by_name_with_folders_first
    end

    def set_folder_from_param
      # TODO: Support hashed_file_id OR remote_file_id
      @folder =
        @revision
        .committed_versions
        .find_by!(file_id: VCS::File.hashid_to_id(params[:id]))

      raise ActiveRecord::RecordNotFound unless @folder.folder?
    end

    def set_folder_from_root
      @folder = VCS::Version.new(file: @master_branch.root.file)
    end

    def set_revision
      @revision = @master_branch.commits.find(params[:revision_id])
    end

    def set_user_can_restore_revision
      @user_can_restore_revision = can?(:restore_revision, @project)
    end
  end
end

app/views/folders/_ancestor.slim
/ render a single ancestor

/ connector icon: >
svg.separator viewBox='0 0 24 24'
  path[fill='currentColor'
       d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z"]

/ link to the ancestor
=<> link_to ancestor.name,
            send(folder_path, *path_parameters, ancestor.hashed_file_id),
            class: "breadcrumb#{ancestor == current_folder ? ' active' : ''}"

app/views/folders/_ancestors.slim
/ render the ancestors as breadcrumbs

nav.breadcrumbs.truncate.gray.lighten-3.black-text.z-depth-0
  .container
    .nav-wrapper
      .col.s12

        / print link back to home/root folder
        = link_to(send(root_folder_path, *path_parameters),
                  class: "breadcrumb home") do
          / home icon
          svg viewBox='0 0 24 24'
            path[fill="currentColor"
                 d="M10,20V14H14V20H19V12H22L12,3L2,12H5V20H10Z"]

        / print each ancestor
        = render partial: 'folders/ancestor',
                collection: ancestors.reverse.push(current_folder.version),
                locals: { current_folder: current_folder,
                          project: project,
                          path_parameters: path_parameters,
                          folder_path: folder_path }

app/views/folders/_file.slim
/ render a single file with diff/change indicator

.file.z-depth-1[
  class=((file.remote_file_id.present? || file.diff.folder?) ? 'hover-effect' : '')
  class=file.diff.symbolic_mime_type
  class=(file.diff.changes.any? ? 'change' : 'no-change')
  class=file.diff.change_types.join(' ')
  class=(file.diff.text_color || 'black-text')
  class=(file.diff.color || 'black')
  title=file.diff.name
]

  = render partial: 'folders/link_to_file_info',
           locals: { file_id: file.diff.hashed_file_id,
                     project: project,
                     path_parameters: path_parameters,
                     file_infos_path: file_infos_path }

  = link_to_file(file, folder_path, path_parameters, class: 'file-link') do


    .indicators
      = render partial: 'folders/file_diff_indicator',
               collection: file.diff.changes,
               as: :file_change

    = image_tag file.diff.thumbnail_image_or_fallback.url,
                alt: 'File icon',
                size: '200',
                class: 'file-thumbnail responsive-img'

    - unless file.diff.thumbnail_image.present?
      .file-thumbnail-fallback.valign-wrapper
        = image_tag file.diff.icon, size: '100'

    .file-title
      .file-icon.left
        = image_tag file.diff.icon, class: 'responsive-img'
      .file-name.truncate = file.diff.name

app/views/folders/_file_diff_indicator.slim
/ render the icon indicotar for this diff/change

span title=file_change.tooltip
  svg.white-text.z-depth-1[class=file_change.color
                           style="width:24px;height:24px"
                           viewBox="0 0 24 24"]
    path fill="currentColor" d=file_change.indicator_icon

app/views/folders/_link_to_file_info.slim
/ Renders the link icon to the file's info page
= link_to send(file_infos_path, *path_parameters, file_id),
          class: 'file-info right white-text gray darken-2',
          title: 'More Options' do
  svg style="width:24px;height:24px" viewBox="0 0 24 24"
    path fill="currentColor" d="M11,9H13V7H11M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M11,17H13V11H11V17Z"

app/views/folders/show.slim
- unless action_name == 'root'
  = render partial: 'folders/ancestors',
           object: @ancestors,
           locals: { current_folder: @folder,
                     project: @project,
                     path_parameters: path_parameters,
                     root_folder_path: root_folder_path,
                     folder_path: folder_path }

.spacing.v48px

.container
  - @children.each do |child|

    = render partial: 'folders/file',
             object: child,
             locals: { project: @project,
                       path_parameters: path_parameters,
                       folder_path: folder_path,
                       file_infos_path: file_infos_path }

/ button for committing changes
- if @user_can_commit_changes
  .fixed-action-btn
    = link_to new_profile_project_revision_path(@project.owner, @project),
              class: 'btn btn-large primary-color primary-color-text'
      | Capture Changes
      span.chip.slim.primary-color-inverse.primary-color-text-inverse
        = @project.uncaptured_changes_count