config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin panel routing, return 404 unless account is admin
  authenticated :account, ->(account) { account.admin? } do
    namespace :admin do
      resources :accounts, :projects
      namespace :profiles do
        resources :users
      end

      # Analytics Dashboard
      mount Blazer::Engine, at: 'analytics', as: :analytics

      root to: 'accounts#index'
    end
  end

  # Error routing
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Static pages
  get '/platform', to: 'static#github_for_documents'

  devise_for :accounts, skip: %i[registrations sessions]

  # Routes for signups
  post '/signup' => 'signups#create'

  # Routes for registration
  if Settings.enable_account_registration
    devise_scope :account do
      get   '/join' => 'devise/registrations#new',
            :as     => :new_registration
      post  '/join' => 'devise/registrations#create',
            :as     => :registration
    end
  end

  # Routes for account management
  devise_scope :account do
    resource :account,
             only: %i[edit update destroy],
             path_names: { edit: '' },
             controller: 'accounts'
    # Stay on /account page after user updates their account
    get '/account', to: 'accounts#edit', as: :account_root
  end

  # Routes for sessions
  devise_scope :account do
    get   '/login'  => 'devise/sessions#new',
          :as       => :new_session
    post  '/login'  => 'devise/sessions#create',
          :as       => :session
    get   '/logout' => 'devise/sessions#destroy',
          :as       => :destroy_session
  end

  # Redirect to login path when user is unauthenticated
  get '/login' => 'devise/sessions#new', :as => :new_account_session

  # Routes for notifications
  resources :notifications, only: %i[index show]

  # Routes for creating new projects
  get   '/projects/new' => 'projects#new',    as: :new_project
  post  '/projects/new' => 'projects#create', as: :projects

  # Routes for user profiles (must be last)
  resources :profiles, path: '/', only: %i[show edit update], param: :handle

  # Routes for existing projects (must be last)
  resources :profiles, path: '/', only: [], param: :handle do
    # Routes for existing projects (must be last)
    resources :projects,
              path: '/', except: %i[index new create], param: :slug do
      # Route for overview
      get 'overview' => 'project_overviews#show', as: :overview
      # Routes for setup
      resource :project_setup, as: 'setup', only: %i[new create show],
                               path: 'setup'
      # Routes for folders
      get 'files' => 'folders#root', as: :root_folder
      resources :folders, only: :show
      # Routes for revisions
      resources :revisions, only: %i[index new create] do
        scope module: 'revisions' do
          get 'files' => 'folders#root', as: :root_folder
          resources :folders, only: :show

          # revision restorations
          post 'restore' => 'restores#create', as: :restores
          get 'restore/status', to: 'restores#show', as: :restore_status,
                                on: :collection

          resources :file_changes, path: 'changes',
                                   controller: 'file_changes',
                                   only: :show
        end
      end
      # Routes for contributions
      resources :contributions, only: %i[index new create show] do
        scope module: 'contributions' do
          # File browsing
          get 'files' => 'folders#root', as: :root_folder
          resources :folders, only: :show

          # Replies
          resources :replies, only: %i[index create]

          # Review
          resource :review, only: :show
          resource :acceptance, path: 'accept', only: :create

          # Routes for file infos
          resources :file_infos, path: 'files/:id/info', only: :index
          resources :force_syncs, path: 'files/:id/sync', only: :create

          # Side-by-side diffs
          resources :file_changes, path: 'changes', only: :show
        end
      end

      # Routes for changes
      resources :file_changes, path: 'changes', only: :show

      # Routes for file infos
      resources :file_infos, path: 'files/:id/info', only: :index
      resources :force_syncs, path: 'files/:id/sync', only: :create
      resources :file_restores, path: 'versions/:id/restore', only: :create
    end
  end

  root 'static#open_collaboration'
end

app/models/notification/revision.rb
# frozen_string_literal: true

class Notification
  # Helper for revision notifications
  class Revision
    include Rails.application.routes.url_helpers
    attr_accessor :revision

    def initialize(revision)
      self.revision = revision
    end

    # The path to the notifying object
    def path
      profile_project_revisions_path(revision.project.owner, revision.project)
    end

    # The recipients for this notification
    def recipients
      recipient_users.map(&:account)
    end

    # The source/originator for this notification
    def source
      revision.author
    end

    private

    def project
      revision.project
    end

    def collaborators_in_project
      [project.owner] + project.collaborators.includes(:account)
    end

    def recipient_users
      (collaborators_in_project - [revision.author]).uniq
    end
  end
end

app/controllers/revision/folders_controller.rb
# frozen_string_literal: true

class Revision
  # File browsing actions for a project revision
  class FoldersController < ApplicationController
    include CanSetProjectContext

    before_action :set_project_where_setup_is_complete
    before_action :authorize_project_access
    before_action :set_revision, only: %i[root show]
    before_action :set_folder_from_root, only: :root
    before_action :set_folder_from_param, only: :show
    before_action :set_children, only: %i[root show]
    before_action :preload_backups_for_children, only: %i[root show]

    def root
      render 'show'
    end

    def show; end

    private

    def preload_backups_for_children
      ActiveRecord::Associations::Preloader.new.preload(
        Array(@children).flat_map(&:file_resource_snapshot),
        backup: :file_resource
      )
    end

    def set_children
      @children =
        @revision.committed_files
                 .includes(file_resource_snapshot: [:file_resource])
                 .in_folder(@folder)
                 .order_by_name_with_folders_first
    end

    def set_folder_from_param
      @folder =
        @revision.committed_files
                 .includes(:file_resource)
                 .find_by!(file_resources: { external_id: params[:id] })
                 .file_resource

      # TODO: Don't check if file resource is folder NOW, check if committed
      # =>    file resource snapshot was folder BACK at commit
      raise ActiveRecord::RecordNotFound unless @folder.folder?
    end

    def set_folder_from_root
      @folder = @project.root_folder
    end

    def set_revision
      @revision = @project.revisions.find(params[:revision_id])
    end
  end
end

app/controllers/revisions/file_changes_controller.rb
# frozen_string_literal: true

module Revisions
  # Controller for project revision file infos
  class FileChangesController < Abstract::FileChangesController
    private

    # Raise error unless we have a modification
    def ensure_modification
      return if @file_diff.modification?

      raise ActiveRecord::RecordNotFound
    end

    # Raise error unless we have content change
    def ensure_content_change
      return if @file_diff.content_change.present?

      raise ActiveRecord::RecordNotFound
    end

    # Set the file diff found within the revision
    def set_file_diff
      @file_diff = @revision.file_diffs.find_by_hashed_file_id!(params[:id])
    end

    def set_branch
      @branch = @master_branch
    end

    def set_object
      @revision = @project.revisions.find(params[:revision_id])
    end
  end
end

app/controllers/revisions/folders_controller.rb
# frozen_string_literal: true

module Revisions
  # File browsing actions for a project revision
  class FoldersController < ApplicationController
    include CanSetProjectContext

    before_action :set_project_where_setup_is_complete
    before_action :authorize_project_access
    before_action :set_revision, only: %i[root show]
    before_action :set_folder_from_root, only: :root
    before_action :set_folder_from_param, only: :show
    before_action :set_children, only: %i[root show]
    before_action :set_ancestors, only: %i[root show]
    before_action :set_user_can_restore_revision

    def root
      render 'show'
    end

    def show; end

    private

    # TODO: Refactor into ancestry generator class
    def set_ancestors
      @ancestors = []
      ancestor =
        @revision.committed_versions
                 .find_by(file_id: @folder.parent_id)

      while ancestor.present?
        @ancestors << ancestor
        ancestor =
          @revision.committed_versions
                   .find_by(file_id: ancestor.parent_id)
      end
    end

    def set_children
      @children =
        @revision.committed_versions
                 .includes(:backup, :thumbnail)
                 .where(parent_id: @folder.file_id)
                 .order_by_name_with_folders_first
    end

    def set_folder_from_param
      # TODO: Support hashed_file_id OR remote_file_id
      @folder =
        @revision
        .committed_versions
        .find_by!(file_id: VCS::File.hashid_to_id(params[:id]))

      raise ActiveRecord::RecordNotFound unless @folder.folder?
    end

    def set_folder_from_root
      @folder = VCS::Version.new(file: @master_branch.root.file)
    end

    def set_revision
      @revision = @master_branch.commits.find(params[:revision_id])
    end

    def set_user_can_restore_revision
      @user_can_restore_revision = can?(:restore_revision, @project)
    end
  end
end

app/controllers/revisions/restores_controller.rb
# frozen_string_literal: true

module Revisions
  # File browsing actions for a project revision
  class RestoresController < ApplicationController
    include CanSetProjectContext

    before_action :set_revision, only: :create
    before_action :authenticate_account!
    before_action :set_project_where_setup_is_complete
    before_action :authorize_project_access
    before_action :authorize_action

    def create
      @master_branch.restore_commit(@revision, author: current_user)

      redirect_to(
        restore_status_profile_project_revisions_path(@project.owner, @project),
        notice: 'Revision is being restored...'
      )
    end

    def show
      @file_restores_remaining =
        Delayed::Job
        .where(queue: :file_restore, delayed_reference_id: @master_branch.id)
        .count

      # Show status page if file restores are remaining
      return unless @file_restores_remaining.zero?

      redirect_to(root_folder_path, notice: 'Revision successfully restored.')
    end

    private

    rescue_from CanCan::AccessDenied do |exception|
      can_can_access_denied(exception)
    end

    def authorize_action
      authorize! :restore_revision, @project
    end

    def can_can_access_denied(exception)
      super || redirect_to(project_revisions_path, alert: exception.message)
    end

    def root_folder_path
      profile_project_root_folder_path(@project.owner, @project)
    end

    def project_revisions_path
      profile_project_revisions_path(@project.owner, @project)
    end

    def set_revision
      @revision = VCS::Commit.find(params[:revision_id])
    end
  end
end

app/controllers/revisions_controller.rb
# frozen_string_literal: true

# Controller for project revisions
class RevisionsController < ApplicationController
  include CanSetProjectContext

  before_action :authenticate_account!, except: :index
  before_action :set_project_where_setup_is_complete
  before_action :authorize_project_access
  before_action :authorize_action, except: :index
  before_action :build_revision, only: :new
  before_action :find_revision, only: :create

  def index
    # TODO: Raise 404 if no revisions exist or redirect
    # TODO: Change variable name from revision to commit
    @revisions =
      @project
      .master_branch
      .commits
      .order(id: :desc)
      .includes(:author)
      .preload_file_diffs_with_versions

    preload_backups_for_file_diffs_in_revisions(@revisions)
  end

  def new
    preload_backups_for_file_diffs_in_revisions(@revision)
  end

  def create
    if @revision.publish(revision_params.except('id'))
      redirect_with_success_to(
        profile_project_root_folder_path(@project.owner, @project)
      )
    else
      preload_backups_for_file_diffs_in_revisions(@revision)
      render :new
    end
  end

  private

  rescue_from CanCan::AccessDenied do |exception|
    can_can_access_denied(exception)
  end

  def authorize_action
    authorize! params[:action].to_sym, :revision, @project
  end

  def build_revision
    commit = @master_branch.commits.create_draft_and_commit_files!(current_user)
    find_revision_by_id(commit.id)
  end

  def can_can_access_denied(exception)
    super || redirect_to(profile_project_path(@project.owner, @project),
                         alert: exception.message)
  end

  def find_revision
    find_revision_by_id(revision_params[:id])
  end

  def find_revision_by_id(id)
    @revision =
      VCS::Commit
      .preload_file_diffs_with_versions
      .find_by!(id: id, branch: @project.master_branch, author: current_user)
  end

  def preload_backups_for_file_diffs_in_revisions(revisions)
    ActiveRecord::Associations::Preloader.new.preload(
      Array(revisions).flat_map(&:file_diffs)
                      .flat_map(&:current_or_previous_version),
      :backup
    )
  end

  def revision_params
    params.require(:revision)
          .permit(:title, :summary, :id, selected_file_change_ids: [])
  end
end

app/views/revisions/_content_change.slim
.content-change

  / If all fragments are retained, do not show a (useless) diff. Show message
  / instead.
  - if content_change.fragments.all?(&:retain?)
    span.fragment
      | Text did not change
      span.help-icon-wrapper.gray-text.text-lighten-1 title='The text content of this file has not changed. The file shows up as modified because other elements - such as styles or images - were modified.'
        svg.help-icon style="width:24px;height:24px;" viewBox="0 0 24 24"
          path fill="currentColor" d="M13,9H11V7H13M13,17H11V11H13M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z"


  / Okay, we have an actual diff. Let's display it.
  - else
    = render partial: 'revisions/content_change_fragment',
             collection: content_change.fragments,
             locals: { truncate_content: true }

    .links
      = link_to 'View side-by-side',
                send(file_change_path, *path_parameters, hashed_file_id),
                link_options.merge(class: 'btn-flat btn-slim grey lighten-2')

app/views/revisions/_content_change_fragment.slim
- if truncate_content && content_change_fragment.retain?
  - content = content_change_fragment.truncated_content(250)
- else
  - content = content_change_fragment.content

- pieces = content.split(/(\n)/).reject(&:empty?)

- pieces.each do |piece|
  / is this a line break?
  - is_linebreak = piece.eql?("\n")
  span.fragment[class=[content_change_fragment.type, ('linebreak' if is_linebreak)]]
    / if so, then draw a enter key symbol and add line break
    - if is_linebreak
      svg viewBox="0 0 24 24"
        path fill="currentColor" d="M19,7V11H5.83L9.41,7.41L8,6L2,12L8,18L9.41,16.58L5.83,13H21V7H19Z"
      br
    - else
      = piece

app/views/revisions/_file_change.slim
/ Renders a single file change of a file

/ Should all links be opened in a new tab?
- link_options = ( all_links_in_new_tab ? { target: '_blank' } : {} )

div.file[class=file_change.symbolic_mime_type
         class=file_change.type]

  = image_tag file_change.icon,
             alt: 'File icon',
             size: '30',
             class: 'img-responsive file-icon'

  - if show_link_to_file_info
   / TODO: Replace file_change with file and replace VCS::File with file.hashed_file_id
   = render partial: 'revisions/link_to_file_info',
            locals: { file_id: file_change.hashed_file_id,
                      project: project,
                      device: :mobile_and_tablet,
                      link_options: link_options }

  span.file-name[class=file_change.text_color]

    span.name-and-description
      / print: filename in bold
      b
        = link_to_file_backup(file_change.current_or_previous_version, revision, project, link_options) do
          = file_change.name

      / print: added/modified/moved/renamed/deleted text
      =< file_change.description

    - if show_link_to_file_info
      = render partial: 'revisions/link_to_file_info',
               locals: { file_id: file_change.hashed_file_id,
                         project: project,
                         device: :desktop,
                         link_options: link_options }

  - if file_change.modification? && file_change.content_change.present?
    = render partial: 'revisions/content_change',
             object: file_change.content_change,
             locals: { hashed_file_id: file_change.hashed_file_id,
                       file_change_path: file_change_path || :profile_project_file_change_path,
                       path_parameters: path_parameters || [project.owner, project],
                       link_options: link_options }

app/views/revisions/_file_change_checkbox.slim
/ Renders a file checkbox around the content

.file-checkbox
  label
    = check_box_tag 'revision[selected_file_change_ids][]',
                    file_change.id,
                    file_change.selected?,
                    id: "checkbox_#{file_change.id}"
    span.file-wrapper
      = yield

app/views/revisions/_file_changes.slim
/ Renders the changes of a file (file diffs)

/ By default, do not wrap each file change inside a layout
- file_change_wrapper ||= false

.revision-diff
  - if file_changes.any?
    = render partial: 'revisions/file_change',
             layout: file_change_wrapper,
             collection: file_changes,
             locals: { project: project,
                       revision: revision,
                       path_parameters: path_parameters,
                       file_change_path: file_change_path,
                       show_link_to_file_info: show_link_to_file_info,
                       all_links_in_new_tab: all_links_in_new_tab }
  - else
    i No files changed.

app/views/revisions/_head.slim
.page-subheading.no-margin-bottom
  .container
    .row.no-margin-bottom
      .col.s12
        p.flow-text.no-margin
          = link_to profile_project_revision_root_folder_path(project.owner, project, revision)
            b.black-text = revision.title
        p.no-margin
          ' captured by
          => link_to profile_path(revision.author)
            = revision.author.name
          ' &middot;
          = link_to profile_project_revisions_path(project.owner, project, anchor: revision),
                    class: 'black-text'
            => time_ago_in_words(revision.created_at)
            | ago

app/views/revisions/_link_to_file_info.slim
/ Renders the link icon to the file's info page
- link = profile_project_file_infos_path(project.owner, project, file_id)

/ for touch devices, always display the info button
- if device == :mobile_and_tablet
  span.right.hide-on-large-only.grey-text
    = link_to link, link_options, class: 'info' do
      svg style="width:24px;height:24px" viewBox="0 0 24 24"
        path fill="currentColor" d="M16,12A2,2 0 0,1 18,10A2,2 0 0,1 20,12A2,2 0 0,1 18,14A2,2 0 0,1 16,12M10,12A2,2 0 0,1 12,10A2,2 0 0,1 14,12A2,2 0 0,1 12,14A2,2 0 0,1 10,12M4,12A2,2 0 0,1 6,10A2,2 0 0,1 8,12A2,2 0 0,1 6,14A2,2 0 0,1 4,12Z"

/ for desktop devices, display info button hover only
- elsif device == :desktop
  span.options-on-hover.hide-on-med-and-down<
    span.gray-text
      | &middot;
    =< link_to 'More', link, link_options.merge(class: 'info gray-text')

app/views/revisions/_restore_button.slim
/ render a button to restore the version/revision

= button_to path_to_restore_action,
            class: 'btn-flat primary-color primary-color-text',
            method: :post
  | Restore

app/views/revisions/_revision_author.slim
.author
  = link_to profile_path(revision_author) do

    = image_tag 'profiles/picture.jpg',
                size: '70',
                class: 'responsive-img circle z-depth-1'

    br

    span.chip.author-name.z-depth-1.white.black-text
      = revision_author.name

app/views/revisions/_revision_diff.slim
/ Renders the changes of a file (file diffs)

.revision-diff
  - if file_diffs.any?
    = render partial: 'revisions/file_diff',
             collection: file_diffs,
             locals: { project: project,
                       show_link_to_file_info: show_link_to_file_info,
                       all_links_in_new_tab: all_links_in_new_tab }
  - else
    i No files changed.

app/views/revisions/_revision_metadata.slim
.metadata
  h5.title.no-margin-top
    = render partial: 'revisions/revision_timestamp',
             locals: { project: project, revision: revision, device: :desktop }
    = link_to( profile_project_revision_root_folder_path(project.owner, project, revision),
               class: 'black-text' )
      b = revision.title

  - if revision.summary.present?
    .summary
      = simple_format html_escape(revision.summary)

app/views/revisions/_revision_timestamp.slim
/ render the revision's timestamp and a direct link to the revision
- if device == :desktop
  - class_tag = 'hide-on-small-only'
  - is_slim   = false
- elsif device == :mobile
  - class_tag = 'hide-on-med-and-up'
  - is_slim   = true

= link_to profile_project_revisions_path(project.owner, project, anchor: revision.id),
          class: class_tag do
  span.chip.right[class=('slim' if is_slim)]
    => time_ago_in_words(revision.created_at)
    | ago

app/views/revisions/index.slim
.container

  .spacing.v32px

  = render partial: 'revision',
           collection: @revisions,
           locals: { project: @project,
                     show_link_to_file_info: true }

.spacing.v48px

app/views/revisions/new.slim
= form_for(@revision, as: :revision, method: :post, url: profile_project_revisions_path(@project.owner, @project)) do |f|

  = hidden_field_tag 'revision[selected_file_change_ids][]', nil

  .page-subheading
    .container
      .row.no-margin-bottom
        .col.s12
          h2 Capture Changes

  .container
    - if @revision.errors.any?
      .row.no-margin-bottom
        .col.s12
          .validation-errors
            = render partial: "error",
                     collection: @revision.errors.full_messages,
                     as: :error

    = f.hidden_field :id

    .row
      .col.s12
        h3.no-margin: span Review Changes
        p.gray-text.text-darken-2.no-margin-top Select changes to capture.
        = render partial: 'file_changes',
                 object: @revision.file_changes,
                 locals: { project: @project,
                           revision: @revision,
                           path_parameters: [@project.owner, @project],
                           file_change_path: :profile_project_file_change_path,
                           show_link_to_file_info: true,
                           all_links_in_new_tab: true,
                           file_change_wrapper: 'file_change_checkbox' }

    .spacing.v32px

    .row
      .col.s12.l12
        .input-field
          = f.text_field :title, placeholder: 'One sentence description of your changes'
          = f.label :title, 'Title'

    .row
      .col.s12.l12
        .input-field
          = f.text_area :summary,
                        rows: 3,
                        placeholder: 'Summarize the changes you have made to files',
                        class: 'materialize-textarea noscript'
          = f.label :summary, 'Summary of Changes (optional)'

    .row
      .col.s12.right-align
        button action='submit' class="btn-large primary-color primary-color-text"
          | Capture Changes

    .spacing.v48px