config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin panel routing, return 404 unless account is admin
  authenticated :account, ->(account) { account.admin? } do
    namespace :admin do
      resources :accounts, :projects
      namespace :profiles do
        resources :users
      end

      # Analytics Dashboard
      mount Blazer::Engine, at: 'analytics', as: :analytics

      root to: 'accounts#index'
    end
  end

  # Error routing
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Static pages
  get '/platform', to: 'static#github_for_documents'

  devise_for :accounts, skip: %i[registrations sessions]

  # Routes for signups
  post '/signup' => 'signups#create'

  # Routes for registration
  if Settings.enable_account_registration
    devise_scope :account do
      get   '/join' => 'devise/registrations#new',
            :as     => :new_registration
      post  '/join' => 'devise/registrations#create',
            :as     => :registration
    end
  end

  # Routes for account management
  devise_scope :account do
    resource :account,
             only: %i[edit update destroy],
             path_names: { edit: '' },
             controller: 'accounts'
    # Stay on /account page after user updates their account
    get '/account', to: 'accounts#edit', as: :account_root
  end

  # Routes for sessions
  devise_scope :account do
    get   '/login'  => 'devise/sessions#new',
          :as       => :new_session
    post  '/login'  => 'devise/sessions#create',
          :as       => :session
    get   '/logout' => 'devise/sessions#destroy',
          :as       => :destroy_session
  end

  # Redirect to login path when user is unauthenticated
  get '/login' => 'devise/sessions#new', :as => :new_account_session

  # Routes for notifications
  resources :notifications, only: %i[index show]

  # Routes for creating new projects
  get   '/projects/new' => 'projects#new',    as: :new_project
  post  '/projects/new' => 'projects#create', as: :projects

  # Routes for user profiles (must be last)
  resources :profiles, path: '/', only: %i[show edit update], param: :handle

  # Routes for existing projects (must be last)
  resources :profiles, path: '/', only: [], param: :handle do
    # Routes for existing projects (must be last)
    resources :projects,
              path: '/', except: %i[index new create], param: :slug do
      # Route for overview
      get 'overview' => 'project_overviews#show', as: :overview
      # Routes for setup
      resource :project_setup, as: 'setup', only: %i[new create show],
                               path: 'setup'
      # Routes for folders
      get 'files' => 'folders#root', as: :root_folder
      resources :folders, only: :show
      # Routes for revisions
      resources :revisions, only: %i[index new create] do
        scope module: 'revisions' do
          get 'files' => 'folders#root', as: :root_folder
          resources :folders, only: :show

          # revision restorations
          post 'restore' => 'restores#create', as: :restores
          get 'restore/status', to: 'restores#show', as: :restore_status,
                                on: :collection

          resources :file_changes, path: 'changes',
                                   controller: 'file_changes',
                                   only: :show
        end
      end
      # Routes for contributions
      resources :contributions, only: %i[index new create show] do
        scope module: 'contributions' do
          # File browsing
          get 'files' => 'folders#root', as: :root_folder
          resources :folders, only: :show

          # Replies
          resources :replies, only: %i[index create]

          # Review
          resource :review, only: :show
          resource :acceptance, path: 'accept', only: :create

          # Routes for file infos
          resources :file_infos, path: 'files/:id/info', only: :index
          resources :force_syncs, path: 'files/:id/sync', only: :create

          # Side-by-side diffs
          resources :file_changes, path: 'changes', only: :show
        end
      end

      # Routes for changes
      resources :file_changes, path: 'changes', only: :show

      # Routes for file infos
      resources :file_infos, path: 'files/:id/info', only: :index
      resources :force_syncs, path: 'files/:id/sync', only: :create
      resources :file_restores, path: 'versions/:id/restore', only: :create
    end
  end

  root 'static#open_collaboration'
end

app/models/project.rb
# frozen_string_literal: true

# Handles projects that belong to a profile (owner)
# rubocop:disable Metrics/ClassLength
class Project < ApplicationRecord
  # Associations
  belongs_to :owner, class_name: 'Profiles::Base'
  has_and_belongs_to_many :collaborators,
                          class_name: 'Profiles::User',
                          association_foreign_key: 'profile_id',
                          validate: false,
                          before_add: :grant_read_access_to_archive,
                          before_remove: :revoke_access_to_archive

  has_one :setup, class_name: 'Project::Setup', dependent: :destroy

  belongs_to :master_branch, class_name: 'VCS::Branch',
                             optional: true,
                             dependent: :destroy

  belongs_to :repository, class_name: 'VCS::Repository',
                          dependent: :destroy,
                          optional: true

  has_many :revisions, class_name: 'VCS::Commit',
                       through: :master_branch, source: :commits

  has_one :archive, class_name: 'VCS::Archive', through: :repository

  has_many :contributions, dependent: :destroy

  # Attributes
  # Do not allow owner change
  attr_readonly :owner_id
  # Set to true to skip archive setup
  attr_accessor :skip_archive_setup

  # Delegations
  delegate :build_archive, to: :repository
  delegate :archive, to: :repository, prefix: true
  delegate :branches, to: :repository
  delegate :in_progress?, :completed?, to: :setup, prefix: true, allow_nil: true
  delegate :files, :uncaptured_changes_count, to: :master_branch

  # Callbacks
  # Auto-generate slug from title
  before_validation :generate_slug_from_title, if: :title?, unless: :slug?
  # Set up repository and master branch
  before_create :create_repository,                     unless: :repository
  before_create :create_master_branch_with_repository,  unless: :master_branch
  # Set up archive for storing file backups
  # TODO: Refactor into background job
  after_create :setup_archive, unless: :skip_archive_setup
  # Make archive public if this project is changing from private to public
  before_update :make_archive_public, if: :making_public?
  # Make archive private if this project is changing from public to private
  before_update :make_archive_private, if: :making_private?

  # Scopes
  # Returns a virtual attribute permission_level that indicates the user's
  # access level for the project: collaboration, view, or none
  scope :with_permission_level, lambda { |profile|
    left_joins(:collaborators).select(
      "projects.*, #{permission_level_sql_for(profile)} AS permission_level"
    ).distinct
  }
  # Projects where profile has permission to view or to collaborate
  scope :where_permission_level_is_collaboration_or_view, lambda { |profile|
    left_joins(:collaborators).where(
      "#{permission_level_sql_for(profile)} IN ('collaboration', 'view')"
    ).distinct
  }
  # Projects where profile is owner or collaborator
  scope :where_profile_is_owner_or_collaborator, lambda { |profile|
    left_joins(:collaborators)
      .where('owner_id = :profile_id ' \
             'OR profiles_projects.profile_id = :profile_id',
             profile_id: profile.id)
      .distinct
  }
  # Projects where setup has been completed
  scope :where_setup_is_complete, lambda {
    joins(:setup).where(project_setups: { is_completed: true })
  }
  # Find project by profile handle and slug
  scope :find_by_handle_and_slug!, lambda { |handle, slug|
    joins(:owner).find_by!(profiles: { handle: handle }, slug: slug)
  }

  # Validations
  # Title & slug must be present
  validates :title, presence: true, length: { maximum: 50 }
  validates :slug, presence: true
  validates :is_public,
            inclusion: {
              in: [true, false],
              message: 'must be public or private'
            }
  # Conduct validations only if slug is present
  with_options if: :slug? do
    validates :slug, length: { maximum: 50 }
    validates :slug,
              format: {
                with:     /\A[a-zA-Z0-9-]+\z/,
                message:  'must contain only letters, numbers, and dashes'
              }
    validates :slug,
              format: {
                with:     /\A[a-zA-Z0-9]/,
                message:  'must begin with a letter or number'
              }
    validates :slug,
              format: {
                with:     /[a-zA-Z0-9]\z/,
                message:  'must end with a letter or number'
              }
    validates :slug,
              format: {
                without:  /\Aedit\z/,
                message:  'is not available'
              }
  end
  # Validate uniqueness unless slug has errors
  validates :slug,
            uniqueness: {
              case_sensitive: true,
              scope: :owner_id
            },
            unless: proc { |project| project.errors[:slug].any? }

  # Returns the SQL statement for calculating the provided profile's
  # permission level on the given project
  def self.permission_level_sql_for(profile)
    profile_id = connection.quote(profile&.id)

    <<~SQL
      (CASE
      WHEN owner_id = #{profile_id}
           OR profiles_projects.profile_id = #{profile_id}
      THEN 'collaboration'
      WHEN is_public THEN 'view'
      ELSE 'none'
      END)
    SQL
  end

  # Virtual attribute calculated when fetching projects using the
  # `.with_permission_level` scope
  def can_collaborate?
    self[:permission_level] == 'collaboration'
  end

  # Virtual attribute calculated when fetching projects using the
  # `.with_permission_level` scope
  def can_view?
    can_collaborate? || self[:permission_level] == 'view'
  end

  def private?
    is_public == false
  end

  def public?
    is_public == true
  end

  # Return true if the setup process for this project has not started
  def setup_not_started?
    setup.nil? ? true : setup.not_started?
  end

  # List of tags, separated by comma
  def tag_list
    tags.join(', ')
  end

  # Set tags by list of tags (must be comma-separated)
  def tag_list=(tag_list)
    self.tags =
      tag_list.split(',')     # Split tag list by comma delimiter
              .map(&:squish)  # Strips spaces and squishes consecutive spaces
              .select(&:present?) # Ignore empty tags
  end

  # Trim whitespaces around title
  def title=(title)
    super(title.try(:strip))
  end

  # Use slug when generating routes
  def to_param
    slug_in_database
  end

  # Updates the `captured_at` timestamp
  # We do not use touch because we do not want to update the updated_at time
  def touch_captured_at
    update_attribute(:captured_at, Time.zone.now)
  end

  private

  # Build master branch for the repository
  def create_master_branch_with_repository
    create_master_branch(repository: repository)
  end

  # Generate the project slug from the title by replacing whitespace with
  # dashes and removing all non-alphanumeric characters
  def generate_slug_from_title
    self.slug =
      title
      .gsub(/[^0-9a-z\s]/i, '') # replace all non-alphanumeric characters
      .strip                    # trim whitespaces
      .tr(' ', '-')             # replace whitespaces with dashes
      .downcase                 # all lowercase
  end

  # Grant view access to archive to the new collaborator
  def grant_read_access_to_archive(collaborator)
    archive&.grant_read_access_to(collaborator.account.email)
  end

  # Remove view access to the archive from the public
  def make_archive_private
    archive&.remove_public_access
  end

  # Grant view access to the archive to the public
  def make_archive_public
    archive&.grant_public_access
  end

  # Return true if the project is changing from public to private
  def making_private?
    private? && is_public_in_database
  end

  # Return true if the project is changing from private to public
  def making_public?
    public? && !is_public_in_database
  end

  # Remove view access to archive from the removed collaborator
  def revoke_access_to_archive(collaborator)
    archive&.revoke_access_from(collaborator.account.email)
  end

  # Set up the archive folder for this project
  # TODO: Needs refactoring. Method is overloaded.
  # =>    Consider extracting first couple lines into #build_archive method.
  # rubocop:disable Metrics/AbcSize
  def setup_archive
    return unless repository.present?

    repository_archive.present? ||
      build_archive(name: title, owner_account_email: owner.account.email)

    return if repository_archive.setup_completed?

    repository_archive.setup
    repository_archive.grant_public_access if public?
    repository_archive.save
  end
  # rubocop:enable Metrics/AbcSize
end
# rubocop:enable Metrics/ClassLength

app/controllers/admin/projects_controller.rb
# frozen_string_literal: true

module Admin
  # Administration controller for managing projects
  class ProjectsController < Admin::ApplicationController
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# Controller for projects
class ProjectsController < ApplicationController
  include CanSetProjectContext

  before_action :authenticate_account!, except: :show
  before_action :build_project, only: %i[new create]
  before_action :assign_create_params_to_project, only: %i[create]
  before_action :set_project, only: %i[show edit update destroy]
  before_action :authorize_action, only: %i[create edit update destroy]
  before_action :authorize_project_access, only: :show
  before_action :set_user_can_create_private_projects, only: %i[new create]

  def new; end

  def create
    if @project.save
      redirect_with_success_to(
        new_profile_project_setup_path(@project.owner, @project)
      )
    else
      render :new
    end
  end

  # Re-route user depending on whether they have permission to collaborate on
  # the project:
  # - Non-Collaborators are redirected to the overview page
  # - Collaborators are redirected to setup/files
  def show
    return redirect_to project_overview_path unless can?(:collaborate, @project)

    # User is a collaborator, determine the correct destination for redirection
    if @project.setup_not_started?
      redirect_to new_profile_project_setup_path(@project.owner, @project)
    elsif @project.setup_in_progress?
      redirect_to profile_project_setup_path(@project.owner, @project)
    else
      redirect_to profile_project_root_folder_path(@project.owner, @project)
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_with_success_to project_overview_path
    else
      render :edit
    end
  end

  def destroy
    if @project.destroy
      redirect_with_success_to profile_path(@project.owner)
    else
      redirect_to project_overview_path,
                  alert: 'An unexpected error occured while deleting the ' \
                         'project.'
    end
  end

  private

  rescue_from CanCan::AccessDenied do |exception|
    case action_name.to_sym
    when :create
      raise StandardError, 'Unauthorized to create private project'
    else
      can_can_access_denied(exception)
    end
  end

  def authorize_action
    authorize! params[:action].to_sym, @project
  end

  def assign_create_params_to_project
    @project.assign_attributes(project_create_params)
  end

  def build_project
    @project = current_user.projects.build
  end

  def can_can_access_denied(exception)
    super || redirect_to(project_overview_path, alert: exception.message)
  end

  def profile_slug
    params[:slug]
  end

  def project_create_params
    params
      .require(:project)
      .permit(:title, :slug, :tag_list, :description, :is_public)
  end

  def project_params
    params
      .require(:project)
      .permit(:title, :slug, :tag_list, :description)
  end

  def project_overview_path
    profile_project_overview_path(@project.owner, @project)
  end

  def set_user_can_create_private_projects
    @user_can_create_private_projects =
      current_user.can_create_private_projects?
  end
end

app/views/projects/_collaborators.slim
.row
  - collaborators.each_slice(2) do |slice|

    - slice.each do |collaborator|

      .col.s6.m3.l2.center-align
        = render partial: 'profiles/profile', object: collaborator

    div class=cycle('hide-on-med-and-up',
                    'hide-on-large-only',
                    'hide-on-med-only',
                    'hide-on-large-only',
                    'hide-on-med-and-up',
                    '')
      .clearfix
      .spacing.v48px

app/views/projects/_form.slim
= form_for [@project.owner.becomes(Profiles::Base), @project], url: url do |f|

  / show input field instead of title
  - content_for :project_title do
    = f.text_field :title, placeholder: 'Project Title', class: 'inherit'
  end

  / only show Overview tab if this is a new record
  - if @project.new_record?
    - content_for :project_tabs do
      div.tab
        a.active Overview
    end

  = render partial: 'projects/head', object: @project, as: :project,
           locals: { active_tab: :overview, can_collaborate: @can_collaborate }

  .project-banner style="background-image: url(#{image_path('projects/banner.jpg')});"

  .spacing.v48px

  .container
    - if @project.errors.any?
      .row
        .col.s12
          .validation-errors
            = render partial: "error", collection: @project.errors.full_messages, as: :error

    .row
      .col.s12.l6
        .input-field.group
          .mock-input.disabled
            = "/#{@project.owner.to_param}/"
          = f.text_field :slug, placeholder: 'Leave blank to auto-generate'
          = f.label :slug, 'Project URL (letters, numbers, and dashes)'

    .row
      .col.s12.input-field
        = f.text_field :tag_list, placeholder: 'Education, Environment, Health, ...'
        = f.label :tag_list, 'Tags (separate by comma)'

    .row
      .col.s12.input-field
        = f.text_area :description,
                      rows: 3,
                      placeholder: 'Describe this project',
                      class: 'materialize-textarea noscript'
        = f.label :description

    .row
      .col.s12
        button action='submit' class="btn-large primary-color primary-color-text"
          = button

app/views/projects/_head.slim
- active_tab ||= nil

.page-heading.primary-color.primary-color-text.no-padding-bottom.no-margin-bottom.z-depth-1
  .container
    .row.no-margin-bottom
      .col.s12

        h1
          - if content_for? :project_title
            = yield :project_title
          - else
            = project.title

        div.tabs.static
          - if content_for? :project_tabs
            = yield :project_tabs
          - else
            div.tab
              = link_to 'Overview', profile_project_overview_path(project.owner, project),
                class: ('active' if active_tab == :overview)
            - if project.setup_not_started? && can_collaborate
              div.tab
                = link_to 'Setup', new_profile_project_setup_path(project.owner, project),
                          class: ('active' if active_tab == :setup)
            - elsif project.setup_in_progress? && can_collaborate
              div.tab
                = link_to 'Setup', profile_project_setup_path(project.owner, project),
                          class: ('active' if active_tab == :setup)
            - elsif project.setup_completed?
              div.tab
                - if can_collaborate
                  = link_to 'Files', profile_project_root_folder_path(project.owner, project),
                            class: ('active' if active_tab == :files)
                - else
                  = link_to 'Files', profile_project_revision_root_folder_path(project.owner, project, project.revisions.last)
              div.tab
                = link_to 'Revisions', profile_project_revisions_path(project.owner, project),
                          class: ('active' if active_tab == :revisions)
              div.tab
                = link_to 'Contributions', profile_project_contributions_path(project.owner, project),
                          class: ('active' if active_tab == :contributions)
              - if can_collaborate
                div.tab
                  = link_to project.master_branch.root.link_to_remote, target: '_blank' do
                    svg style="width:24px;height:24px" viewBox="0 0 24 24" class="left"
                      path fill="currentColor" d="M14,3V5H17.59L7.76,14.83L9.17,16.24L19,6.41V10H21V3M19,19H5V5H12V3H5C3.89,3 3,3.9 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V12H19V19Z"
                    | Open in Drive
                  end

app/views/projects/_project.slim
.col.s12.m6.l4
  = link_to url_for([project.owner.becomes(Profiles::Base), project]), class: 'card hoverable project'
    .card-title.truncate
      = image_tag project.owner.picture(:medium),
                  size: '40',
                  class: 'responsive-img circle left title-image',
                  title: project.owner.name

      span.title.truncate = project.title

      / when there are uncaptured changes in project, show small indicator
      - if project.can_collaborate? && project.uncaptured_changes_count.nonzero?
        .uncaptured-changes-indicator.primary-color title='Project has uncaptured changes'

      p.subtitle.truncate.gray-text.text-darken-2
        ' Updated
        => time_ago_in_words(project.captured_at)
        | ago

    .card-content
      p
        - if project.description.present?
          = truncate(project.description, length: 200)
        - else
          | No description.

    .card-action
      span.btn-flat Open
      - if project.private?
        span.lock-icon-wrapper.right.gray-text.text-darken-2 title='Project is private'
          svg.lock-icon style="width:24px;height:24px" viewBox="0 0 24 24"
            path fill="currentColor" d="M12,17A2,2 0 0,0 14,15C14,13.89 13.1,13 12,13A2,2 0 0,0 10,15A2,2 0 0,0 12,17M18,8A2,2 0 0,1 20,10V20A2,2 0 0,1 18,22H6A2,2 0 0,1 4,20V10C4,8.89 4.9,8 6,8H7V6A5,5 0 0,1 12,1A5,5 0 0,1 17,6V8H18M12,3A3,3 0 0,0 9,6V8H15V6A3,3 0 0,0 12,3Z"

app/views/projects/access_unauthorized.slim
.spacing.v64px

.not-found.container.center-align

  .row
    .col.s12
      svg.icon viewBox="0 0 24 24"
        path fill="currentColor" d="M12,17C10.89,17 10,16.1 10,15C10,13.89 10.89,13 12,13A2,2 0 0,1 14,15A2,2 0 0,1 12,17M18,20V10H6V20H18M18,8A2,2 0 0,1 20,10V20A2,2 0 0,1 18,22H6C4.89,22 4,21.1 4,20V10C4,8.89 4.89,8 6,8H7V6A5,5 0 0,1 12,1A5,5 0 0,1 17,6V8H18M12,3A3,3 0 0,0 9,6V8H15V6A3,3 0 0,0 12,3Z"

  .row
    .col.s12
      h1 Hi there!
      p.flow-text
        | You are not authorized to access this project.
        br
        br
        - if account_signed_in?
          | Ask the owner to add you as a project collaborator.
        - else
          => link_to 'Log in', new_session_path
          | and try again.

  .row
    .col.s12
      .divider

  .row
    .col.s12
      p
        | Prejudice is a burden that confuses the past, threatens the future and renders the present inaccessible.
        br
        em - Maya Angelou

app/views/projects/edit.slim
= render partial: 'form', \
         locals: { \
           url: nil, \
           button: 'Save' \
         }

.spacing.v16px

.container
  h3 Delete Project
  .row
    .col.s12.l6
      = button_to('Delete Project',
                url_for([@project.owner.becomes(Profiles::Base), @project]),
                data: { confirm: 'Are you sure?' },
                method: :delete,
                class: 'btn primary-color primary-color-text')

.spacing.v48px

app/views/projects/new.slim
= form_for [@project.owner.becomes(Profiles::Base), @project], url: url_for(@project) do |f|

  .page-heading.primary-color.primary-color-text.z-depth-1
    .container
      .row.no-margin-bottom
        .col.s12
          h1 New Project

  .container
    - if @project.errors.any?
      .row
        .col.s12
          .validation-errors
            = render partial: "error", collection: @project.errors.full_messages, as: :error

    .row
      .col.s12.l12
        .input-field
          h2.no-margin
            = f.text_field :title, placeholder: 'Title', class: 'inherit'
    .row
      .col.s12
        .section.no-padding-top
          .section.no-padding-top
            label
              = f.radio_button :is_public, true, checked: @project.public?, class: 'with-gap public'
              span.black-text
                b Public
                br
                | Anyone can see this project. Only you can make changes.

          .section.no-padding-top
            label
              = f.radio_button :is_public, false, checked: @project.private?, class: 'with-gap private', disabled: !@user_can_create_private_projects
              span class=[@user_can_create_private_projects ? 'black-text' : 'gray-text']
                b Private
                - unless @user_can_create_private_projects
                  = mail_to Settings.support_email, \
                            subject: "Upgrade to premium: #{@current_account.user.handle}", \
                            body: "Hi there,\n\n\nI would like to update my account #{@current_account.email} to a paid plan.\n\n\nCheers,\n#{@current_account.user.name}"
                    span.chip.slim.primary-color.primary-color-text.inline
                      svg.icon style="width:24px;height:24px" viewBox="0 0 24 24"
                        path fill="currentColor" d="M12,17.27L18.18,21L16.54,13.97L22,9.24L14.81,8.62L12,2L9.19,8.62L2,9.24L7.45,13.97L5.82,21L12,17.27Z"
                      | Premium | Upgrade
                br
                | You choose who can see this project and make changes.

    .row
      .col.s12
        button action='submit' class="btn-large primary-color primary-color-text"
          | Create

app/views/projects/show.slim
= render partial: 'projects/head', object: @project, as: :project,
         locals: { active_tab: :overview }

.project-banner style="background-image: url(#{image_path('projects/banner.jpg')});"

.container
  .action-bar.right
    - if @user_can_edit_project
      = link_to( \
          url_for([:edit, @project.owner, @project]), \
          id: 'edit_project', \
          class: 'btn-floating btn-large primary-color primary-color-text')
        svg viewBox="0 0 24 24"
          path fill="currentColor" d="M20.71,7.04C21.1,6.65 21.1,6 20.71,5.63L18.37,3.29C18,2.9 17.35,2.9 16.96,3.29L15.12,5.12L18.87,8.87M3,17.25V21H6.75L17.81,9.93L14.06,6.18L3,17.25Z"

.spacing.v32px

- if @project.tags.any?
  .container
    .row.no-margin-bottom
      .col.s12
        - @project.tags.each do |tag|
          .chip.tag.primary-color.primary-color-text
            = tag_case tag


- if @project.description.present?
  .container
    .row.no-margin-bottom
      .col.s12
        .flow-text
          = simple_format html_escape(@project.description)


.container
  / TODO: Rename to Collaborators (or another name) once we implement the teams
  /       feature
  h3 Project Team
  = render partial: 'collaborators',
           object: @collaborators.to_a.prepend(@project.owner)