config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin panel routing, return 404 unless account is admin
  authenticated :account, ->(account) { account.admin? } do
    namespace :admin do
      resources :accounts, :projects
      namespace :profiles do
        resources :users
      end

      # Analytics Dashboard
      mount Blazer::Engine, at: 'analytics', as: :analytics

      root to: 'accounts#index'
    end
  end

  # Error routing
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Static pages
  get '/platform', to: 'static#github_for_documents'

  devise_for :accounts, skip: %i[registrations sessions]

  # Routes for signups
  post '/signup' => 'signups#create'

  # Routes for registration
  if Settings.enable_account_registration
    devise_scope :account do
      get   '/join' => 'devise/registrations#new',
            :as     => :new_registration
      post  '/join' => 'devise/registrations#create',
            :as     => :registration
    end
  end

  # Routes for account management
  devise_scope :account do
    resource :account,
             only: %i[edit update destroy],
             path_names: { edit: '' },
             controller: 'accounts'
    # Stay on /account page after user updates their account
    get '/account', to: 'accounts#edit', as: :account_root
  end

  # Routes for sessions
  devise_scope :account do
    get   '/login'  => 'devise/sessions#new',
          :as       => :new_session
    post  '/login'  => 'devise/sessions#create',
          :as       => :session
    get   '/logout' => 'devise/sessions#destroy',
          :as       => :destroy_session
  end

  # Redirect to login path when user is unauthenticated
  get '/login' => 'devise/sessions#new', :as => :new_account_session

  # Routes for notifications
  resources :notifications, only: %i[index show]

  # Routes for creating new projects
  get   '/projects/new' => 'projects#new',    as: :new_project
  post  '/projects/new' => 'projects#create', as: :projects

  # Routes for user profiles (must be last)
  resources :profiles, path: '/', only: %i[show edit update], param: :handle

  # Routes for existing projects (must be last)
  resources :profiles, path: '/', only: [], param: :handle do
    # Routes for existing projects (must be last)
    resources :projects,
              path: '/', except: %i[index new create], param: :slug do
      # Route for overview
      get 'overview' => 'project_overviews#show', as: :overview
      # Routes for setup
      resource :project_setup, as: 'setup', only: %i[new create show],
                               path: 'setup'
      # Routes for folders
      get 'files' => 'folders#root', as: :root_folder
      resources :folders, only: :show
      # Routes for revisions
      resources :revisions, only: %i[index new create] do
        scope module: 'revisions' do
          get 'files' => 'folders#root', as: :root_folder
          resources :folders, only: :show

          # revision restorations
          post 'restore' => 'restores#create', as: :restores
          get 'restore/status', to: 'restores#show', as: :restore_status,
                                on: :collection

          resources :file_changes, path: 'changes',
                                   controller: 'file_changes',
                                   only: :show
        end
      end
      # Routes for contributions
      resources :contributions, only: %i[index new create show] do
        scope module: 'contributions' do
          # File browsing
          get 'files' => 'folders#root', as: :root_folder
          resources :folders, only: :show

          # Replies
          resources :replies, only: %i[index create]

          # Review
          resource :review, only: :show
          resource :acceptance, path: 'accept', only: :create

          # Routes for file infos
          resources :file_infos, path: 'files/:id/info', only: :index
          resources :force_syncs, path: 'files/:id/sync', only: :create

          # Side-by-side diffs
          resources :file_changes, path: 'changes', only: :show
        end
      end

      # Routes for changes
      resources :file_changes, path: 'changes', only: :show

      # Routes for file infos
      resources :file_infos, path: 'files/:id/info', only: :index
      resources :force_syncs, path: 'files/:id/sync', only: :create
      resources :file_restores, path: 'versions/:id/restore', only: :create
    end
  end

  root 'static#open_collaboration'
end

app/models/notifications/contributions/accept.rb
# frozen_string_literal: true

module Notifications
  module Contributions
    # Helper for contribution notifications
    class Accept
      include Rails.application.routes.url_helpers
      attr_accessor :contribution
      attr_writer :source

      delegate :project, to: :contribution

      def initialize(contribution, source: nil)
        self.contribution = contribution
        self.source = source
      end

      # The path to the notifying object
      def path
        profile_project_contribution_path(project.owner, project, contribution)
      end

      # The recipients for this notification
      def recipients
        recipient_users.map(&:account)
      end

      # The source/originator for this notification
      def source
        @source ||= contribution.acceptor
      end

      # The notification's title
      def title
        "#{source.name} accepted a contribution in #{project.title}"
      end

      private

      def collaborators_in_project
        [project.owner] + project.collaborators.includes(:account)
      end

      def recipient_users
        (collaborators_in_project +
         contribution.repliers.includes(:account) +
         [contribution.creator] -
         [contribution.acceptor]).uniq
      end
    end
  end
end

app/models/notifications/contributions/create.rb
# frozen_string_literal: true

module Notifications
  module Contributions
    # Helper for contribution notifications
    class Create
      include Rails.application.routes.url_helpers
      attr_accessor :contribution
      attr_writer :source

      delegate :project, to: :contribution

      def initialize(contribution, source: nil)
        self.contribution = contribution
        self.source = source
      end

      # The path to the notifying object
      def path
        profile_project_contribution_path(project.owner, project, contribution)
      end

      # The recipients for this notification
      def recipients
        recipient_users.map(&:account)
      end

      # The source/originator for this notification
      def source
        @source ||= contribution.creator
      end

      # The notification's title
      def title
        "#{source.name} created a contribution in #{project.title}"
      end

      private

      def collaborators_in_project
        [project.owner] + project.collaborators.includes(:account)
      end

      def recipient_users
        (collaborators_in_project - [contribution.creator]).uniq
      end
    end
  end
end

app/controllers/contributions/acceptances_controller.rb
# frozen_string_literal: true

module Contributions
  # Controller for reviewing changes suggested by a contribution
  class AcceptancesController < ApplicationController
    include CanSetProjectContext

    before_action :authenticate_account!
    before_action :set_project_where_setup_is_complete
    before_action :authorize_project_access
    before_action :set_contribution
    before_action :authorize_action
    before_action :find_revision

    # TODO: Refactor
    # rubocop:disable Metrics/MethodLength
    def create
      if @contribution.accept(revision: @revision, acceptor: current_user)
        # Successfully accepted
        redirect_with_success_to(
          profile_project_root_folder_path(@project.owner, @project),
          notice: 'Contribution successfully accepted. ' \
                  'Suggested changes are being applied...'
        )
      else
        # Error occurred while accepting contribution
        @user_can_accept_contribution = true
        @revision.preload_file_diffs_with_versions
        render 'contributions/reviews/show_suggested_changes',
               layout: 'contributions/reviews'
      end
    end
    # rubocop:enable Metrics/MethodLength

    private

    rescue_from CanCan::AccessDenied do |exception|
      can_can_access_denied(exception)
    end

    def authorize_action
      authorize! :accept, @contribution
    end

    def can_can_access_denied(exception)
      super || redirect_to(contribution_review_path, alert: exception.message)
    end

    def contribution_review_path
      profile_project_contribution_review_path(
        @project.owner, @project, @contribution
      )
    end

    def find_revision
      @revision = VCS::Commit.find_by!(
        id: contribution_params[:revision_id],
        branch: @contribution.branch,
        author: current_user,
        is_published: false
      )
    end

    def set_contribution
      @contribution = @project.contributions.find(params[:contribution_id])
    end

    def contribution_params
      params.require(:contribution).permit(:revision_id)
    end
  end
end

app/controllers/contributions/file_changes_controller.rb
# frozen_string_literal: true

module Contributions
  # Controller for project file infos
  class FileChangesController < Abstract::FileChangesController
    private

    def set_branch
      @branch = @contribution.branch
    end

    def set_object
      @contribution = @project.contributions.find(params[:contribution_id])
    end
  end
end

app/controllers/contributions/file_infos_controller.rb
# frozen_string_literal: true

module Contributions
  # Controller for project file infos within a contribution
  class FileInfosController < Abstract::FileInfosController
    private

    def link_path_prefix
      'profile_project_contribution_'
    end

    def path_parameters
      [@project.owner, @project, @contribution]
    end

    def set_branch
      @branch = @contribution.branch
    end

    def set_object
      @contribution = @project.contributions.find(params[:contribution_id])
    end

    def set_user_can_force_sync_files
      @user_can_force_sync_files = can?(:force_sync, @contribution)
    end

    # TODO: Only contribution creator can restore files in contribution
    def set_user_can_restore_files
      @user_can_restore_files = false
      # @user_can_restore_files = can?(:restore_file, @project)
    end

    # Any user can view files in branch for contributions
    def set_user_can_view_file_in_branch
      @user_can_view_file_in_branch = true
    end
  end
end

app/controllers/contributions/folders_controller.rb
# frozen_string_literal: true

module Contributions
  # File browsing actions for a project contribution
  class FoldersController < Abstract::FoldersController
    private

    def link_path_prefix
      'profile_project_contribution_'
    end

    def path_parameters
      [@project.owner, @project, @contribution]
    end

    def require_authentication?
      false
    end

    def set_object
      @contribution = @project.contributions.find(params[:contribution_id])
    end

    def set_branch
      @branch = @contribution.branch
    end
  end
end

app/controllers/contributions/force_syncs_controller.rb
# frozen_string_literal: true

module Contributions
  # Controller for force syncing files of contributions
  class ForceSyncsController < Abstract::ForceSyncsController
    private

    def authorize_action
      authorize! :force_sync, @contribution
    end

    def file_info_path
      profile_project_contribution_file_infos_path(
        @project.owner,
        @project,
        @contribution,
        @file || params[:id]
      )
    end

    def set_branch
      @branch = @contribution.branch
    end

    def set_object
      @contribution = @project.contributions.find(params[:contribution_id])
    end
  end
end

app/controllers/contributions/replies_controller.rb
# frozen_string_literal: true

module Contributions
  # Controller for replies to contributions
  class RepliesController < ApplicationController
    include CanSetProjectContext

    before_action :authenticate_account!, except: :index
    before_action :set_project_where_setup_is_complete
    before_action :authorize_project_access
    before_action :find_contribution
    before_action :authorize_action, except: :index
    before_action :set_replies, only: :index
    before_action :build_reply
    before_action :set_user_can_reply_to_contribution, only: :index

    def index; end

    def create
      if @reply.update(reply_params)
        redirect_with_success_to(contribution_replies_path)
      else
        set_replies
        set_user_can_reply_to_contribution
        render 'index'
      end
    end

    private

    rescue_from CanCan::AccessDenied do |exception|
      can_can_access_denied(exception)
    end

    def authorize_action
      authorize! :reply, @contribution
    end

    def can_can_access_denied(exception)
      super || redirect_to(contribution_replies_path, alert: exception.message)
    end

    def build_reply
      @reply = @contribution.replies.build(author: current_user)
    end

    def contribution_replies_path
      profile_project_contribution_replies_path(
        @project.owner, @project, @contribution
      )
    end

    def find_contribution
      @contribution = @project.contributions.find(params[:contribution_id])
    end

    def set_replies
      @replies = @contribution.replies.includes(:author)
    end

    def set_user_can_reply_to_contribution
      @user_can_reply_to_contribution = can?(:reply, @contribution)
    end

    def reply_params
      params.require(:reply).permit(:content)
    end
  end
end

app/controllers/contributions/reviews_controller.rb
# frozen_string_literal: true

module Contributions
  # Controller for reviewing changes suggested by a contribution
  class ReviewsController < ApplicationController
    include CanSetProjectContext

    before_action :set_project_where_setup_is_complete
    before_action :authorize_project_access
    before_action :set_contribution
    before_action :set_revision, if: :contribution_accepted?
    before_action :prepare_revision_for_acceptance,
                  unless: :contribution_accepted?
    before_action :set_user_can_accept_contribution,
                  unless: :contribution_accepted?

    def show
      if contribution_accepted?
        render 'show_accepted_changes'
      else
        render 'show_suggested_changes'
      end
    end

    private

    def contribution_accepted?
      @contribution.accepted?
    end

    def prepare_revision_for_acceptance
      @contribution
        .prepare_revision_for_acceptance(author: current_user_or_fallback)
    end

    def set_contribution
      @contribution = @project.contributions.find(params[:contribution_id])
    end

    def set_revision
      @revision =
        @contribution.accepted_revision.tap(&:preload_file_diffs_with_versions)
    end

    def set_user_can_accept_contribution
      @user_can_accept_contribution = can?(:accept, @contribution)
    end

    # Return the current user or fall back to the contribution creator
    # TODO: Remove when we refactor author requirement from commit
    def current_user_or_fallback
      current_user || @contribution.creator
    end
  end
end

app/controllers/contributions_controller.rb
# frozen_string_literal: true

# Controller for project contributions
class ContributionsController < ApplicationController
  include CanSetProjectContext

  before_action :authenticate_account!, except: %i[index show]
  before_action :set_project_where_setup_is_complete
  before_action :authorize_project_access
  before_action :build_contribution, only: %i[new create]
  before_action :authorize_action, only: %i[new create]
  before_action :find_contribution, only: :show

  def index
    @contributions = @project.contributions.order(id: :desc).includes(:creator)
  end

  def new; end

  def create
    if @contribution.setup(contribution_params)
      redirect_with_success_to(
        profile_project_contribution_path(
          @project.owner, @project, @contribution
        )
      )
    else
      render :new
    end
  end

  def show
    redirect_to profile_project_contribution_replies_path(
      @project.owner, @project, @contribution
    )
  end

  private

  rescue_from CanCan::AccessDenied do |exception|
    can_can_access_denied(exception)
  end

  def authorize_action
    authorize! params[:action].to_sym, @contribution
  end

  def build_contribution
    @contribution = @project.contributions.build(
      creator: current_user,
      origin_revision: @project.revisions.last
    )
  end

  def find_contribution
    @contribution = @project.contributions.find(params[:id])
  end

  def can_can_access_denied(exception)
    super || redirect_to(
      profile_project_contributions_path(@project.owner, @project),
      alert: exception.message
    )
  end

  def contribution_params
    params.require(:contribution).permit(:title, :description)
  end
end

app/views/contributions/_contribution.slim
/ render a single contribution

.row.contribution id=contribution.id

  .spacing.v8px

  = render partial: 'contribution_timestamp',
           locals: { project: project, contribution: contribution, device: :mobile }

  .spacing.v8px


  .col.l2.m3.s12.center-align
    = render partial: 'profiles/profile',
             object: contribution.creator

  .col.l10.m9.s12
    h5.title.no-margin-top
      = render partial: 'contribution_timestamp',
               locals: { project: project, contribution: contribution, device: :desktop }
      = link_to( profile_project_contribution_path(project.owner, project, contribution),
                 class: 'black-text' )
        b = contribution.title

    - if contribution.accepted?
      span.chip.green.lighten-4.green-text.text-darken-3
        span.icon
          svg style="width:24px;height:24px" viewBox="0 0 24 24"
            path fill="currentColor" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"
        | Accepted

    .description
      = simple_format html_escape(contribution.description)

.spacing.v16px
.divider
.spacing.v16px

app/views/contributions/_contribution_timestamp.slim
/ render the contribution's timestamp
- if device == :desktop
  - class_tag = 'hide-on-small-only'
  - is_slim   = false
- elsif device == :mobile
  - class_tag = 'hide-on-med-and-up'
  - is_slim   = true

div class=[class_tag]
  span.chip.right[class=('slim' if is_slim)]
    => time_ago_in_words(contribution.created_at)
    | ago

app/views/contributions/_head.slim
.page-subheading.gray.lighten-3.no-padding-bottom.no-margin-bottom
  .container
    .row.no-margin-bottom
      .col.s12
        p.flow-text.no-margin
          b = contribution.title
        p.no-margin
          ' proposed by
          => link_to profile_path(contribution.creator)
            = contribution.creator.name
          | &middot;
          =<> time_ago_in_words(contribution.created_at)
          | ago
          - if contribution.accepted?
            = ' '
            | &middot; accepted

        div.tabs.static.no-margin-top
          div.tab
            = link_to 'Discussion', profile_project_contribution_path(project.owner, project, contribution),
                       class: ('active' if active_tab == :discussion)
          div.tab
            = link_to 'Files', profile_project_contribution_root_folder_path(project.owner, project, contribution),
                       class: ('active' if active_tab == :files)
          div.tab
            = link_to 'Review', profile_project_contribution_review_path(project.owner, project, contribution),
                       class: ('active' if active_tab == :review)
          - if contribution.files.root&.link_to_remote.present?
            div.tab
              = link_to contribution.files.root.link_to_remote, target: '_blank' do
                svg style="width:24px;height:24px" viewBox="0 0 24 24" class="left"
                  path fill="currentColor" d="M14,3V5H17.59L7.76,14.83L9.17,16.24L19,6.41V10H21V3M19,19H5V5H12V3H5C3.89,3 3,3.9 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V12H19V19Z"
                | Open in Drive

app/views/contributions/index.slim
.container

  .spacing.v32px

  = render partial: 'contribution',
           collection: @contributions,
           locals: { project: @project }

.spacing.v48px

/ button for committing changes
.fixed-action-btn
  = link_to 'New Contribution',
      new_profile_project_contribution_path(@project.owner, @project),
      class: 'btn btn-large primary-color primary-color-text'

app/views/contributions/new.slim
= form_for(@contribution, method: :post, url: profile_project_contributions_path(@project.owner, @project)) do |f|

  .page-subheading.gray.lighten-3
    .container
      .row.no-margin-bottom
        .col.s12
          h2 New Contribution

  .container
    - if @contribution.errors.any?
      .row.no-margin-bottom
        .col.s12
          .validation-errors
            = render partial: "error",
                     collection: @contribution.errors.full_messages,
                     as: :error

    .spacing.v32px

    .row
      .col.s12.l12
        .input-field
          = f.text_field :title
          = f.label :title, 'Title'

    .row
      .col.s12.l12
        .input-field
          = f.text_area :description,
                        rows: 3,
                        class: 'materialize-textarea noscript'
          = f.label :description, 'Description'

    .row
      .col.s12.right-align
        button action='submit' class="btn-large primary-color primary-color-text"
          | Create Contribution

    .spacing.v48px